CREATE DATABASE snizannadb;

CREATE USER 'lox'@'localhost' IDENTIFIED BY 'Qwerty1-';

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, INDEX, DROP, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES ON snizannadb.* TO 'lox'@'localhost';